name: najot_pay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  connectivity_plus: ^6.0.3
  change_app_package_name: ^1.1.0
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.0
  path_provider: ^2.0.0
  flutter_timezone: ^1.0.4
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  fluttertoast: ^8.2.5


  my_utils:
    path: packages/my_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.otf
        - asset: assets/fonts/inter/Inter-Bold.otf
        - asset: assets/fonts/inter/Inter-Italic.otf
        - asset: assets/fonts/inter/Inter-Light.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-SemiBold.otf
